version: "2.1"

volumes:
  pgdata:

services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
    restart: "no"
    ports:
      - 3100:3100
    environment:
      PORT: 3100
      DB_HOST: 172.17.0.1
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:13.1
    ports:
      - 5432:5432
    restart: "no"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=changeme
      - POSTGRES_DB=ohjelmistoprojekti
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
